[build]
  publish = "out"

[[redirects]]
  from = "/links.html"
  to = "/links.html"
  status = 200
  force = true

[[redirects]]
  from = "/visitingcard"
  to = "https://hello.uptownproperties.in/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
